### ISSUE TITLE
variants to try/pilot

### ISSUE THREAD

**Issue by anne-urai** [anne-urai/plot_gitlab_ibl_data#12]

**Comment by anne-urai** [comment]
| Dimension | Mouse IBL | York MEG/fMRI | Options for Leiden | Decision? |
|--------|--------|--------|--------|--------|
| Contrast set | `0, 0.0625, 0.125, 0.25, 1` | ? | see Annika's initial pilot |   |
| Contrast baseline | 0 (detection task) | Pedestal | Pedestal(s) / dynamic noise |   |
| Biased blocks | `80/20` probability, in uncued blocks of 40-100 trials | Cued prior | Cued vs uncued prior |   |
| Instructions | none | full | vary: full vs none | |
| Session length | 45-60 minutes, no breaks | breaks each 8 minute | Breaks vs. no breaks | | 
| Feedback | Single-trial reward/time-out | ? | Single-trial sound | |

**Comment by cami-uche-enwe** [comment]
In Alex's version:
- contrast set: `0.5, 0.52, 0.55, 0.6, 0.7`
- contrast deltas: `0, 0.02, 0.05, 0.1, 0.2`
- pedestal: `0.5`

**Comment by anne-urai** [comment]
Closed; still write all of this down https://github.com/users/anne-urai/projects/1/views/1?pane=issue&itemId=59133976
