### ISSUE TITLE
Program offline task

### ISSUE THREAD

**Issue by cami-uche-enwe** [anne-urai/plot_gitlab_ibl_data#13]

**Comment by cami-uche-enwe** [comment]
- [ ] create new repo
- [ ] give anne maintainer access
- [ ] build basic task
- [ ] refine instructions
- [ ] scale stimuli to lab monitors

**Comment by cami-uche-enwe** [comment]
Current version doesn't allow to hid mouse cursor when running offline (bug fix in progress but so far no updates). This is only an issue for the attention check in the instructions, should we downgrade the psychopy version or modify the attention check to only use keypress? Not sure if downgrading would cause compatibility issues in the lab computer?

**Comment by cami-uche-enwe** [comment]
> Current version doesn't allow to hid mouse cursor when running offline (bug fix in progress but so far no updates). This is only an issue for the attention check in the instructions, should we downgrade the psychopy version or modify the attention check to only use keypress? Not sure if downgrading would cause compatibility issues in the lab computer?

Actually switching versions seems to be an issue for multiple people on the forum lately, maybe it's best to avoid that

**Comment by cami-uche-enwe** [comment]
> Actually switching versions seems to be an issue for multiple people on the forum lately, maybe it's best to avoid that

Scratch that! Switching versions didn't work but I solved in another way, we can keep things as they were :)

**Comment by anne-urai** [comment]
- [ ] import ITI from pregenerated file
- [ ] glitch fix (double check in lab)
- [ ] code timeout as [0,1] or [True, False]
- [ ] save position of the dot, per frame

**Comment by cami-uche-enwe** [comment]
https://github.com/cami-uche-enwe/human_IBL_cursor
