### ISSUE TITLE
check if monitors can be automatically set to 75Hz

### ISSUE THREAD

**Issue by anne-urai** [anne-urai/plot_gitlab_ibl_data#17]

**Comment by anne-urai** [comment]
ask Maureen

**Comment by cami-uche-enwe** [comment]
ask if data/files get actually wiped at the end of the day. if not, then no need to re upload and save data every day

**Comment by cami-uche-enwe** [comment]
- Monitors can be set to 74.973Hz max - and it's very easy to do through each PC's settings
- Lab support said to assume that data will get wiped at the end of every day - but unofficially told me this is not yet properly implemented. But to avoid risking losing any data, best to backup to J: drive at the end of each day anyways
