### ISSUE TITLE
walk-in week questions

### ISSUE THREAD

**Issue by anne-urai** [anne-urai/plot_gitlab_ibl_data#18]

**Comment by anne-urai** [comment]
- [ ] does every experiment get its own cubicles?

**Comment by anne-urai** [comment]
Checklist 
- room light to p.5
- no phone in the cubicle
- ask people to move the desk to their height
- move keyboard away 
- print a sheet where we write the participant numbers

**Comment by cami-uche-enwe** [comment]
- all admin stuff for credits should be handled within the experiment, so that experimenter doesn't have to do anything - use Qualtrics: add link to Qualtrics from experiment?
- schedule: excel schedule from henk on teams
- flyers: collect on tuesday 16/4 in 2B05 (henk's office)
-
